// Layout definitions matching the real Tavant Corporate Template 2025
// 23 layouts extracted from the .potx file

const LAYOUTS = {
  title_cover: {
    id: "title_cover",
    name: "Title Slide",
    layoutRef: "Layout 1: Title Slide_B",
    description: "Dark background with tech imagery, orange Tavant logo, large title (up to 3 lines), optional subtitle and date. Use as the FIRST slide.",
    fields: ["title", "subtitle", "date"],
  },
  agenda: {
    id: "agenda",
    name: "Agenda",
    layoutRef: "Layout 2: Agenda",
    description: "Dark data-waves background, orange numbered talking points (up to 6 items), decorative cubes corner element.",
    fields: ["items"],
  },
  breaker_ai: {
    id: "breaker_ai",
    name: "Breaker — AI",
    layoutRef: "Layout 3: BREAKER SLIDE 2",
    description: "Full-bleed AI brain imagery, bold orange title, optional key points. Use to introduce new sections.",
    fields: ["title", "key_points"],
  },
  breaker_cloud: {
    id: "breaker_cloud",
    name: "Breaker — Cloud",
    layoutRef: "Layout 4: BREAKER SLIDE 3",
    description: "Full-bleed cloud/abstract imagery, bold orange title. Section divider with cloud/data theme.",
    fields: ["title", "key_points"],
  },
  breaker_abstract: {
    id: "breaker_abstract",
    name: "Breaker — Abstract",
    layoutRef: "Layout 5: BREAKER SLIDE 4",
    description: "Full-bleed abstract lines imagery, bold orange title. Section divider with abstract/tech theme.",
    fields: ["title", "key_points"],
  },
  blank: {
    id: "blank",
    name: "Blank",
    layoutRef: "Layout 6: Blank",
    description: "White slide with only footer bar and logo. For custom content.",
    fields: [],
  },
  title_only: {
    id: "title_only",
    name: "Title Only",
    layoutRef: "Layout 7: Title Only",
    description: "White slide with just a title at top. Open area for custom content below.",
    fields: ["title"],
  },
  title_only_dark: {
    id: "title_only_dark",
    name: "Title Only (Dark)",
    layoutRef: "Layout 8: Title Only - Grey",
    description: "Dark grey (#222222) slide with title at top. Open area for custom content below.",
    fields: ["title"],
  },
  content_dark: {
    id: "content_dark",
    name: "Title + Content (Dark)",
    layoutRef: "Layout 9: Title + Content - Grey",
    description: "Dark grey slide with title and content area. For detailed text on dark background.",
    fields: ["title", "body"],
  },
  content: {
    id: "content",
    name: "Title + Content",
    layoutRef: "Layout 10: Title + Content",
    description: "White slide with title and large content area. General-purpose content slide.",
    fields: ["title", "body"],
  },
  title_subtitle: {
    id: "title_subtitle",
    name: "Title + Subtitle",
    layoutRef: "Layout 11: Title + Subtitle",
    description: "White slide with title (24pt bold) and orange subtitle (18pt). For section introductions.",
    fields: ["title", "subtitle"],
  },
  two_column: {
    id: "two_column",
    name: "Title + 2-Column Content",
    layoutRef: "Layout 12: Title + 2-Column Content",
    description: "White slide with title, subtitle, and two equal content columns. Good for comparisons.",
    fields: ["title", "subtitle", "left_content", "right_content"],
  },
  title_subtitle_content: {
    id: "title_subtitle_content",
    name: "Title + Subtitle + Content",
    layoutRef: "Layout 13: Title + Subtitle + Content",
    description: "White slide with title, orange subtitle, and full-width content area below. Most versatile layout.",
    fields: ["title", "subtitle", "body"],
  },
  multi_case_study: {
    id: "multi_case_study",
    name: "Multi-Case Study (4 columns)",
    layoutRef: "Layout 16: Multi-Case Study",
    description: "Black background, 4 equal columns with image placeholders and text. For showcasing 4 case studies or capabilities.",
    fields: ["title", "subtitle", "columns"],
  },
  image_content_a: {
    id: "image_content_a",
    name: "Image + Content A",
    layoutRef: "Layout 17: Image + Content A",
    description: "White slide with content on left and large image placeholder on right. For case studies.",
    fields: ["title", "subtitle", "body", "image_description"],
  },
  image_content_b: {
    id: "image_content_b",
    name: "Image + Content B",
    layoutRef: "Layout 15: Image + Content B",
    description: "Black background with image left, 2 topic boxes right, and content area below. For detailed analysis.",
    fields: ["title", "subtitle", "topic_1", "topic_2", "body"],
  },
  image_grid: {
    id: "image_grid",
    name: "Image + Content Grid",
    layoutRef: "Layout 18: Image + Content C",
    description: "Photo/image top, 2x3 grid of text blocks below. Title overlaid on image. For capabilities overview.",
    fields: ["title", "subtitle", "grid_items"],
  },
  three_column_images: {
    id: "three_column_images",
    name: "3-Column with Images",
    layoutRef: "Layout 19: Images + Content D",
    description: "Black background with 3 columns. Each column has: dark box with large semi-transparent number (01/02/03) + orange left accent bar, then a white card below with orange left accent + orange bottom border. Pass columns as [{title, description}]. Title and description render on separate lines automatically.",
    fields: ["title", "subtitle", "columns"],
  },
  chart: {
    id: "chart",
    name: "Content + Chart",
    layoutRef: "Layout 20: Content + Chart",
    description: "Grey (#77787B) background, content left with key takeaway box, chart right. For data-driven slides.",
    fields: ["title", "subtitle", "body", "takeaway", "chart_data"],
  },
  timeline_vertical: {
    id: "timeline_vertical",
    name: "Timeline (Vertical)",
    layoutRef: "Layout 21: Timeline 1",
    description: "Black background, vertical year timeline on right, 3 stat/content blocks, descriptive text. For KPIs over time.",
    fields: ["title", "subtitle", "body", "blocks", "year_highlight"],
  },
  timeline_horizontal: {
    id: "timeline_horizontal",
    name: "Timeline (Horizontal)",
    layoutRef: "Layout 22: Timeline 2",
    description: "Orange (#F26F26) background, horizontal timeline with 8 date points and alternating content blocks. For roadmaps.",
    fields: ["title", "subtitle", "milestones"],
  },
  multi_quote: {
    id: "multi_quote",
    name: "Multi-Quote / Testimonials",
    layoutRef: "Layout 23: Multi-Quote",
    description: "Black background, 3 rows with logo/image slots left and quote text right. For client testimonials.",
    fields: ["title", "subtitle", "quotes"],
  },
  thank_you: {
    id: "thank_you",
    name: "Thank You",
    layoutRef: "Layout 14: Thank You",
    description: "Dark background with abstract imagery, large THANK YOU text, office locations, contact info. Use as the LAST slide.",
    fields: ["contact_email", "contact_website", "contact_phone"],
  },
};

module.exports = LAYOUTS;
